export const DOCUMENT_TEMPLATES = {
  parcel: [
    { id: 'label', name: 'Shipping Label', required: true, autoGenerated: true },
    { id: 'receipt', name: 'Payment Receipt', required: true, autoGenerated: true }
  ],
  seafreight: [
    { id: 'commercial_invoice', name: 'Commercial Invoice', required: true, customerUpload: false },
    { id: 'packing_list', name: 'Packing List', required: true, customerUpload: false },
    { id: 'certificate_of_origin', name: 'Certificate of Origin', required: true, customerUpload: true },
    { id: 'fumigation_certificate', name: 'Fumigation Certificate', required: false, customerUpload: true },
    { id: 'free_sale_certificate', name: 'Free Sale Certificate', required: false, customerUpload: true },
    { id: 'inspection_certificate', name: 'Inspection Certificate', required: false, customerUpload: true }
  ],
  airfreight: [
    { id: 'commercial_invoice', name: 'Commercial Invoice', required: true, customerUpload: false },
    { id: 'packing_list', name: 'Packing List', required: true, customerUpload: false }
  ],
  fcl: [
    { id: 'commercial_invoice', name: 'Commercial Invoice', required: true, customerUpload: false },
    { id: 'packing_list', name: 'Packing List', required: true, customerUpload: false },
    { id: 'certificate_of_origin', name: 'Certificate of Origin', required: true, customerUpload: true }
  ],
  lcl: [
    { id: 'commercial_invoice', name: 'Commercial Invoice', required: true, customerUpload: false },
    { id: 'packing_list', name: 'Packing List', required: true, customerUpload: false }
  ]
} as const;

export type ServiceKey = keyof typeof DOCUMENT_TEMPLATES;
export type DocumentTemplate = (typeof DOCUMENT_TEMPLATES)[ServiceKey][number];

